#  NUMERICAL PYTHON (NUMPY)

**import numpy**

In [ ]:
import numpy as np

Checking Numpy Version

In [3]:
print(np.__version__)

1.26.1


Create a Numpy ndarray 

In [2]:
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


0-D Arrays

In [4]:
import numpy as np
arr = np.array(99)
print(arr)

99


1-D Array

In [5]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2-D Array

In [6]:
import numpy as np
arr=np.array([[1,2,3,4],[6,7,8,9]])
print(arr)

[[1 2 3 4]
 [6 7 8 9]]


3-D Array

In [8]:
arr=np.array([[[1,2,3],[4,5,6]],[[8,9,0],[11,23,44]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9  0]
  [11 23 44]]]


Check number of  dimensions

In [13]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3,4],[6,7,8,9]])
d=np.array([[[1,2,3],[4,5,6]],[[8,9,0],[11,23,44]]])
print(a.ndim,"dimension")
print(b.ndim,"dimension")
print(c.ndim,"dimension")
print(d.ndim,"dimension")


0 dimension
1 dimension
2 dimension
3 dimension


Access Array Elements

In [18]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])
print(arr[2]+arr[3])
print(arr[2]-arr[1])
print(arr[1]*arr[3])

1
7
1
8


Accass 2-D array

In [22]:
arr=np.array([[1,2,3,4],[9,7,8,6]])
print("3rd element on 1st row:",arr[0,2])
print("2nd element on 2nd row :",arr[1,1])
#print(arr[2,0]) it rise index error

3rd element on 1st row: 3
2nd element on 2nd row : 7


Range 

In [32]:
a=np.array (range(10))
b=np.array(range(2,10))
c=np.array(range(2,20,5))
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[ 2  7 12 17]


Create an array filled with 0's

In [38]:
import numpy as np 
print(np.zeros(3))

[0. 0. 0.]


Array filled with 1's

In [39]:
print(np.ones(3))

[1. 1. 1.]


Full Array

In [48]:
import numpy as np
x=np.full((3,3),50)  #np.full(shape,fillvalue)
print(x)
y=np.full((3,3),[10,11,2004])
print(y)

[[50 50 50]
 [50 50 50]
 [50 50 50]]
[[  10   11 2004]
 [  10   11 2004]
 [  10   11 2004]]


Specifying data type

In [56]:
x=np.array(range(10),dtype=np.float64)
y=np.array(range(10),dtype=np.int32)
print(x)
print(y)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


Sorting

In [57]:
import numpy as np
arr=np.array([11,23,1,2,3,34,55,77,6,5,44,55,3,44])
print(np.sort(arr))

[ 1  2  3  3  5  6 11 23 34 44 44 55 55 77]


Concatenate

In [58]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
x=np.concatenate((a,b))
print(x)

[1 2 3 4 5 6 7 8]


In [10]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
x=np.concatenate((x,y),axis=0)
print(x)
                  

[[1 2]
 [3 4]
 [5 6]]


Numpy array dimension, shape , size

In [11]:
import numpy as np 
x=np.array([[[1,2,3,4],[0,9,8,7],[12,13,14,5],[44,55,66,77],[99,8,77,33]]])
print(x.ndim)
print(x.shape)
print(x.size)


3
(1, 5, 4)
20


Reshape

In [15]:
a=np.arange(6)
print(a)
b=a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


Indexing and slicing

In [16]:
import numpy as np
d=np.array([11,33,55,66,77,88,99,0,1,2,3,4,5,6,7])
print(d[0])
print(d[0:2])
print(d[1:])
print(d[:1])
print(d[:-1])
print(d[-2:])
print(d[2:-4])

11
[11 33]
[33 55 66 77 88 99  0  1  2  3  4  5  6  7]
[11]
[11 33 55 66 77 88 99  0  1  2  3  4  5  6]
[6 7]
[55 66 77 88 99  0  1  2  3]


In [17]:
x=np.array([[[1,2,3,4],[0,9,8,7],[12,13,14,5],[44,55,66,77],[99,8,77,33]]])
print(x[x<=6])
print(x[x>=6])


[1 2 3 4 0 5]
[ 9  8  7 12 13 14 44 55 66 77 99  8 77 33]


In [20]:
a=np.array([[[1,2,3,4],[0,9,8,7],[12,13,14,5],[44,55,66,77],[99,8,77,33]]])
print(a[::])
print(a[0,0:2])

[[[ 1  2  3  4]
  [ 0  9  8  7]
  [12 13 14  5]
  [44 55 66 77]
  [99  8 77 33]]]
[[1 2 3 4]
 [0 9 8 7]]


## AGGREATION

In [22]:
import numpy as np
a=np.sum([1,2,3])
print("Sum",a)
b=np.average([1,2,3])
print("Average",b)
c=np.min([1,2,3])
print("min",c)
d=np.max([1,2,3])
print("max",c)
e=np.prod([1,2,3])
print("product",e)
f=np.mean([1,2,3])
print("mean",f)


Sum 6
Average 2.0
min 1
max 1
product 6
mean 2.0


maximum()

In [23]:
a=np.array([19,22,33,44,55])
b=np.array([12,55,33,99,33])
print(np.maximum(a,b))

[19 55 33 99 55]


### Matrix Operation using Numpy  

Matrix Addition

In [24]:
import numpy as np
x=([[1,2,4],[5,6,7],[8,9,10]])
y=([[3,4,5],[6,19,20],[21,23,45]])
print (np.add(x,y))

[[ 4  6  9]
 [11 25 27]
 [29 32 55]]


Matrix Multiplication

In [25]:
import numpy as np #dot multiplication
x=([[1,2,4],[5,6,7],[8,9,10]])
y=([[3,4,5],[6,19,20],[21,23,45]])
print(np.dot(x,y))


[[ 99 134 225]
 [198 295 460]
 [288 433 670]]


In [26]:
import numpy as np
x=([[1,2,4],[5,6,7],[8,9,10]])
y=([[3,4,5],[6,19,20],[21,23,45]])
print(np.multiply(x,y))


[[  3   8  20]
 [ 30 114 140]
 [168 207 450]]


Transpose of matrix

In [27]:
import numpy as np
x=([[1,2,4],[5,6,7],[8,9,10]])
y=([[3,4,5],[6,19,20],[21,23,45]])
print(np.array(x))
print()
print("transepose of matrix is: ")
print(np.transpose(x))


[[ 1  2  4]
 [ 5  6  7]
 [ 8  9 10]]

transepose of matrix is: 
[[ 1  5  8]
 [ 2  6  9]
 [ 4  7 10]]


Zero matrix

In [28]:
import numpy as np
x=np.zeros((3,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Once matrix

In [29]:
import numpy as np
x= np.ones((3,3),dtype=int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


numpy operations

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([5,6,7,8,9,])
print("addition of two series:",x+y)
print("sub",x-y)
print("multi:",x*y)
print("division:",x/y)

addition of two series: [ 6  8 10 12 14]
sub [-4 -4 -4 -4 -4]
multi: [ 5 12 21 32 45]
division: [0.2        0.33333333 0.42857143 0.5        0.55555556]


List to numpy by appending list

In [ ]:
import numpy as np
n=int(input("enter the element"))
l=[]
for i in range (n):
  e=int(input("ente the values"))
  l.append(e)
print(l)
print(np.array(l))
tupl=(1,2,3,4,5)
print(np.array(tupl))

List to numpy 

In [1]:
import numpy as np
list=[1,2,3,4,5.88,66]
print(list)
print("the one dimensional array are :")
print(np.array(list))


[1, 2, 3, 4, 5.88, 66]
the one dimensional array are :
[ 1.    2.    3.    4.    5.88 66.  ]


### RANDOM

In [5]:
from numpy import random
x=random.randint(100)
print(x)

13


In [6]:
x=random.randint(100,size=(3,4))
print(x)

[[69 68 43 82]
 [43 84 97 89]
 [16  3 92 70]]


Creating random 5 flots

In [7]:
from numpy import random 
x=random.rand(5)
print(x)

[0.21675284 0.07955377 0.71373429 0.64827883 0.93841325]


2-D with three rows 5 random numbers

In [8]:
x=random.rand(3,5)
print(x)

[[0.88555408 0.98516178 0.39657976 0.54899711 0.63440155]
 [0.74781216 0.93250048 0.2475626  0.83760464 0.31065886]
 [0.86657569 0.00569901 0.52979538 0.74766254 0.40693499]]


Random number from array

In [9]:
x=random.choice([3,5,6,7,8,9,0])
print(x)

6


### Numpy logs

function perform a log at the base 2 log2()

In [13]:
import numpy as np
arr = np.arange(1,9)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.        ]


In [16]:
#it performs log at base 10
arr= np.arange(1,9)
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999]


In [18]:
#log at base e
arr= np.arange(1,9)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154]


##### Finding LCM in two numbers

In [19]:
import numpy as np 
num1=6
num2=9
x=np.lcm(num1,num2)
print(x)

18


##### Finding GCD

In [20]:
import numpy as np 
num1=6
num2=9
x=np.gcd(num1,num2)
print(x)

3


##### NUMPY SET OPERATION

Finding union

In [22]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


Intersection

In [23]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2)
print(newarr)

[3 4]
